FROM python:3.5

#RUN apt-get update && apt-get install openssl python3-openssl -y

COPY ./requirements.txt /.
COPY ./requirements_dev.txt /.

RUN /bin/bash -c 'pip3 install -r /requirements.txt && \
                    pip3 install -r requirements_dev.txt'
